# Generated by Django 3.1.5 on 2023-01-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='party_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_bill_to', models.CharField(max_length=200)),
                ('mailing_name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=280)),
                ('country', models.CharField(max_length=200)),
                ('gst_reg_type', models.CharField(max_length=200)),
                ('gstn_un', models.CharField(max_length=200)),
                ('states', models.CharField(max_length=200)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
            ],
        ),
    ]
