# Generated by Django 3.1.5 on 2023-01-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_party_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_details',
            name='place_of_supply',
            field=models.CharField(default='Kerala', max_length=200),
        ),
    ]
