# Generated by Django 3.1.5 on 2023-01-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_party_details_place_of_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispatch_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_no', models.IntegerField(blank=True, null=True)),
                ('dispatch_doc_no', models.IntegerField(blank=True, null=True)),
                ('dispatched_throught', models.CharField(max_length=200, null=True)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('carrier_name_agent', models.CharField(max_length=200, null=True)),
                ('bill_of_lading', models.CharField(max_length=200, null=True)),
                ('mototr_vehicle_no', models.CharField(max_length=200, null=True)),
                ('date1', models.CharField(max_length=200, null=True)),
                ('date2', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
