# Generated by Django 3.1.5 on 2023-01-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_dispatch_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch_detail',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
    ]
