# Generated by Django 3.1.5 on 2023-01-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_dispatch_detail_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_details',
            name='dispatch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dispatch_detail'),
        ),
    ]
