# Generated by Django 3.1.5 on 2023-01-24 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_party_details_dispatch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_ac_name', models.CharField(max_length=200)),
                ('current_bal_party_ac', models.IntegerField()),
                ('sales_ledger', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sales_voucher_invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('name_of_item', models.CharField(max_length=200)),
                ('party_ac_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sales_voucher')),
            ],
        ),
    ]
