# Generated by Django 3.1.5 on 2023-02-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_sales_voucher_sales_voucher_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.FileField(blank=True, null=True, upload_to='')),
                ('name_of_item', models.CharField(max_length=200)),
                ('quantity', models.FileField(blank=True, null=True, upload_to='')),
                ('rate', models.FileField(blank=True, null=True, upload_to='')),
                ('per', models.FileField(blank=True, null=True, upload_to='')),
                ('amount', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
