# Generated by Django 3.1.5 on 2023-02-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_sales_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='dispatch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dispatch_detail'),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='party_detail_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.party_details'),
        ),
    ]
