# Generated by Django 3.1.5 on 2023-02-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20230202_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
