# Generated by Django 3.1.5 on 2023-02-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_sales_invoice_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_voucher_invoice',
            name='party_ac_name',
        ),
        migrations.DeleteModel(
            name='sales_voucher',
        ),
        migrations.DeleteModel(
            name='sales_voucher_invoice',
        ),
    ]
