# Generated by Django 3.1.5 on 2023-02-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20230208_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_voucher_stock_item_allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('quantity', models.FileField(blank=True, null=True, upload_to='')),
                ('rate', models.FileField(blank=True, null=True, upload_to='')),
                ('per', models.FileField(blank=True, null=True, upload_to='')),
                ('amount', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='sales_invoice',
            name='location',
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='inv_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='sales_item_allocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sales_voucher_stock_item_allocation'),
        ),
    ]
