# Generated by Django 3.1.5 on 2023-02-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20230208_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_itemcreation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='under',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
