# Generated by Django 3.1.5 on 2023-02-15 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20230210_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_invoice',
            old_name='sales_item_allocation',
            new_name='sales_voucher_stock_item_allocation',
        ),
        migrations.AddField(
            model_name='sales_voucher_stock_item_allocation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
        migrations.AddField(
            model_name='sales_voucher_stock_item_allocation',
            name='dispatch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dispatch_detail'),
        ),
        migrations.AddField(
            model_name='sales_voucher_stock_item_allocation',
            name='party_detail_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.party_details'),
        ),
    ]
