# Generated by Django 3.1.5 on 2023-03-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20230322_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='per',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales_voucher_stock_item_allocation',
            name='per',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_voucher_stock_item_allocation',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
