# Generated by Django 3.1.5 on 2023-03-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20230322_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_invoice',
            name='sales_voucher_stock_item_allocation',
        ),
        migrations.AddField(
            model_name='sales_voucher_stock_item_allocation',
            name='sales_invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sales_invoice'),
        ),
    ]
