# Generated by Django 3.1.5 on 2023-04-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20230420_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='party_ac_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
